'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ValpoEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ValpoEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property vista_aseo_tbk() As DbSet(Of vista_aseo_tbk)
    Public Overridable Property vista_pago_aseo_ext() As DbSet(Of vista_pago_aseo_ext)
    Public Overridable Property vista_pago_jpl() As DbSet(Of vista_pago_jpl)
    Public Overridable Property vista_pago_provisorias() As DbSet(Of vista_pago_provisorias)
    Public Overridable Property Vista_pagos_Convenio() As DbSet(Of Vista_pagos_Convenio)
    Public Overridable Property vista_pat_com_jc() As DbSet(Of vista_pat_com_jc)
    Public Overridable Property vista_patcom_tbk() As DbSet(Of vista_patcom_tbk)
    Public Overridable Property vista_pcv_jc() As DbSet(Of vista_pcv_jc)
    Public Overridable Property Vista_pcv_transbank() As DbSet(Of Vista_pcv_transbank)

End Class
