'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EncabezadoIngresosDiario
    Public Property Ano_Proceso As Short
    Public Property Codigo_Area As Short
    Public Property NumeroCaja As Short
    Public Property Orden_Ingreso As Integer
    Public Property IDOrden_Ingreso As Short
    Public Property Item_Pago As Short
    Public Property Fecha_Emision As Nullable(Of Date)
    Public Property Fecha_Vencimiento As Nullable(Of Date)
    Public Property Rut As String
    Public Property Nombre As String
    Public Property Placa_Vehiculo As String
    Public Property Rol_Patente As String
    Public Property Rol_Propiedad As String
    Public Property EmitidoPor As String
    Public Property Glosa As String
    Public Property Fecha_OrdenIngreso As Nullable(Of Date)
    Public Property Numero_OrdenIngreso As Nullable(Of Double)
    Public Property FormaDePago As Nullable(Of Short)
    Public Property NumeroCheque As Nullable(Of Double)
    Public Property MontoCheque As Nullable(Of Double)
    Public Property RutCheque As String
    Public Property FonoCheque As String
    Public Property GlosaPago As String
    Public Property Banco As String
    Public Property Rol As String
    Public Property Año As Nullable(Of Double)
    Public Property Cuota As Nullable(Of Double)
    Public Property Periodo As String
    Public Property Cod_Act_Eco As String
    Public Property Tipo_Tributo As String
    Public Property Ano_OrdenIngreso As String
    Public Property NroConvenio As String
    Public Property Tipo_Tarjeta As Nullable(Of Short)
    Public Property Codigo_Tarjeta As String
    Public Property Rut_Tarjeta As String
    Public Property Nombre_Tarjeta As String
    Public Property Numero_Transaccion As String
    Public Property NombreCheque As String
    Public Property Lectura_CBarras_Cheque As String
    Public Property Plaza As String
    Public Property Cta_Cte As String
    Public Property Lectura_CBarras_Tarjeta As String
    Public Property NumeroValeVista As String
    Public Property BancoValeVista As String
    Public Property MontoValeVista As Nullable(Of Double)
    Public Property NombreValeVista As String
    Public Property Fecha_Vcto_Cheque As Nullable(Of Date)
    Public Property Glosa2 As String
    Public Property Glosa3 As String
    Public Property Fecha_Pagos_Tarjeta_Conciliado As Nullable(Of Date)
    Public Property Monto_Tarjeta As Nullable(Of Double)
    Public Property Pagado_ConOrdenIngreso As Nullable(Of Double)
    Public Property Pagado_ConIDOrdenIngreso As Nullable(Of Short)
    Public Property Numero_Licencia As Nullable(Of Double)
    Public Property idUnidadHabitacional As Nullable(Of Integer)
    Public Property Folio_Unico As Nullable(Of Double)
    Public Property Total_OrdenIngreso As Nullable(Of Double)
    Public Property Cod_LugarDePago As Nullable(Of Integer)
    Public Property Extranjero As Nullable(Of Short)
    Public Property Folio_Fisico As Nullable(Of Double)
    Public Property Estado_Folio As Nullable(Of Boolean)
    Public Property Ano_de_Permiso As Nullable(Of Short)
    Public Property Forma_de_Pago_Permiso As Nullable(Of Short)
    Public Property Tipo_Vehiculo As Nullable(Of Short)
    Public Property URLBoletinElectronico As String
    Public Property EstadoItSolution As String

End Class
