'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PATCOM_Maestro_Contribuyente_Vista
    Public Property RUT As String
    Public Property NOMBRE As String
    Public Property DIRECCION As String
    Public Property FONO1 As String

End Class
