'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Consulta
    Partial Public Class RecuperacionCirculacion

        '''<summary>
        '''Control grd_pcv.
        '''</summary>
        Protected WithEvents grd_pcv As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''Control grd_tgr.
        '''</summary>
        Protected WithEvents grd_tgr As Global.System.Web.UI.WebControls.GridView

    End Class
End Namespace
