'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vista_aseo_tbk
    Public Property Cont_Propietario As String
    Public Property tbk_num_tarjeta As String
    Public Property tbk_venc_tarjeta As String
    Public Property tbk_fec_autorizacion As String
    Public Property tbk_fec_hora_autorizacion As Nullable(Of Date)
    Public Property tbk_total_pago As Nullable(Of Integer)
    Public Property idsesion As String
    Public Property rol As String
    Public Property ano As Integer
    Public Property cuota As Integer
    Public Property valor As Nullable(Of Integer)
    Public Property ipc As Nullable(Of Integer)
    Public Property multa As Nullable(Of Integer)
    Public Property idext As String
    Public Property tbk_tipo_pago As String
    Public Property tbk_codigo_autorizacion As String
    Public Property tbk_respuesta As String
    Public Property tbk_orden_de_compra As String
    Public Property Total_Cuota As Nullable(Of Integer)
    Public Property Cont_Rut As String
    Public Property Cont_Direccion As String
    Public Property Email As String
    Public Property enviado As Nullable(Of Boolean)
    Public Property tbk_id_sesion As String

End Class
