'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vista_pcv_jc
    Public Property folio As Nullable(Of Integer)
    Public Property totalpago As String
    Public Property estado As String
    Public Property patente As String
    Public Property fecha_pago As Nullable(Of Date)
    Public Property idsesion As String
    Public Property ano As Nullable(Of Integer)
    Public Property rut As String
    Public Property email As String
    Public Property url As String
    Public Property poliza_seguro As String
    Public Property tipo_pago As Nullable(Of Integer)
    Public Property nom_banco As String
    Public Property idext As String
    Public Property id As Integer
    Public Property datetime As Nullable(Of Date)
    Public Property permiso_imprimir As Nullable(Of Boolean)
    Public Property idoperacion As String
    Public Property idtransaccion As String
    Public Property id_transaccion As Integer
    Public Property ipc As Nullable(Of Integer)
    Public Property multa As Nullable(Of Integer)
    Public Property total_patente As Nullable(Of Integer)

End Class
