'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vista_pago_aseo_ext
    Public Property idext As String
    Public Property idoperacion As String
    Public Property idtransaccion As String
    Public Property rut_tes As String
    Public Property formulario As Nullable(Of Integer)
    Public Property folio As Nullable(Of Integer)
    Public Property totalpago As String
    Public Property cod_banco As Nullable(Of Integer)
    Public Property nom_banco As String
    Public Property fecha_pago As Nullable(Of Date)
    Public Property Correo As String
    Public Property ano_proceso As Short
    Public Property NumeroArriendo As Integer
    Public Property RUT As String
    Public Property periodo As Short
    Public Property ipc As Nullable(Of Integer)
    Public Property multa As Nullable(Of Integer)
    Public Property idsesion As String
    Public Property FechaVenci As Nullable(Of Date)
    Public Property montoCargo As Nullable(Of Integer)
    Public Property estado As String
    Public Property NOMBRES As String

End Class
