'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vista_pagos_Convenio
    Public Property cod_banco As Nullable(Of Integer)
    Public Property nom_banco As String
    Public Property fecha_pago As Nullable(Of Date)
    Public Property ano_proceso As Short
    Public Property n_convenio As Short
    Public Property cuota As Short
    Public Property folio As Nullable(Of Integer)
    Public Property rut As String
    Public Property formulario As Nullable(Of Integer)
    Public Property status As String
    Public Property idoperacion As String
    Public Property idtransaccion As String
    Public Property Monto As Nullable(Of Double)
    Public Property ipc As Nullable(Of Integer)
    Public Property multa As Nullable(Of Integer)
    Public Property totalpago As String
    Public Property rut_completo As String
    Public Property Nombre As String
    Public Property estado As String
    Public Property Rol_Patente As Nullable(Of Integer)
    Public Property Rol_Aseo As String
    Public Property Placa As String
    Public Property email As String

End Class
