'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Vista_pcv_transbank
    Public Property tbk_idsesion As String
    Public Property folio As Nullable(Of Integer)
    Public Property patente As String
    Public Property email As String
    Public Property poliza_seguro As String
    Public Property permiso_imprimir As Nullable(Of Boolean)
    Public Property tbk_total_pago As Nullable(Of Integer)
    Public Property url As String
    Public Property tbk_fec_hora_autorizacion As Nullable(Of Date)
    Public Property tbk_fec_autorizacion As String
    Public Property ano As Nullable(Of Integer)
    Public Property tipo_pago As Nullable(Of Integer)
    Public Property tbk_orden_de_compra As String
    Public Property tbk_codigo_autorizacion As String
    Public Property tbk_tipo_pago As String
    Public Property tbk_respuesta As String
    Public Property rut As String
    Public Property tbk_num_tarjeta As String
    Public Property tbk_tokenws As String
    Public Property validation_code_agile As String
    Public Property ipc As Nullable(Of Integer)
    Public Property multa As Nullable(Of Integer)
    Public Property total_patente As Nullable(Of Integer)

End Class
