'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vista_pat_com_jc
    Public Property rut As String
    Public Property rol As String
    Public Property ano As Nullable(Of Integer)
    Public Property semestre As Nullable(Of Integer)
    Public Property url As String
    Public Property email As String
    Public Property id_session As String
    Public Property code As String
    Public Property msgdesc As String
    Public Property version As Nullable(Of Integer)
    Public Property fromaddress As String
    Public Property toaddress As String
    Public Property refaddress As Nullable(Of Integer)
    Public Property idoperacion As String
    Public Property idtransaccion As String
    Public Property formulario As Nullable(Of Integer)
    Public Property folio As Nullable(Of Integer)
    Public Property vencimiento As Nullable(Of Date)
    Public Property totalpago As String
    Public Property cod_banco As Nullable(Of Integer)
    Public Property nom_banco As String
    Public Property fecha_pago As Nullable(Of Date)
    Public Property estado As String
    Public Property idext As String
    Public Property id As Integer
    Public Property datetime As Nullable(Of Date)
    Public Property id_agile As Nullable(Of Integer)
    Public Property validation_code_agile As String
    Public Property ipc As Nullable(Of Integer)
    Public Property multa As Nullable(Of Integer)
    Public Property total_patente As Nullable(Of Integer)

End Class
