'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vista_patcom_tbk
    Public Property id_transaccion As Integer
    Public Property rut As String
    Public Property rol As String
    Public Property ano As Nullable(Of Integer)
    Public Property semestre As Nullable(Of Integer)
    Public Property url As String
    Public Property email As String
    Public Property id_session As String
    Public Property id_agile As Nullable(Of Integer)
    Public Property validation_code_agile As String
    Public Property tbk_num_tarjeta As String
    Public Property tbk_venc_tarjeta As String
    Public Property tbk_fec_autorizacion As String
    Public Property tbk_fec_hora_autorizacion As Nullable(Of Date)
    Public Property tbk_total_pago As Nullable(Of Integer)
    Public Property tbk_tipo_pago As String
    Public Property tbk_codigo_autorizacion As String
    Public Property tbk_orden_de_compra As String
    Public Property ipc As Nullable(Of Integer)
    Public Property interes As Nullable(Of Integer)
    Public Property total_patente As Nullable(Of Integer)
    Public Property tbk_respuesta As String
    Public Property idext As String
    Public Property folio As Nullable(Of Integer)

End Class
