'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vista_pago_jpl
    Public Property id_session As String
    Public Property folio As Nullable(Of Integer)
    Public Property rut As String
    Public Property nombre As String
    Public Property rol As String
    Public Property monto_rol As String
    Public Property detalle As String
    Public Property fecha_emision As Nullable(Of Date)
    Public Property correo As String
    Public Property idext As String
    Public Property idoperacion As String
    Public Property idtransaccion As String
    Public Property vencimiento As Nullable(Of Date)
    Public Property totalpago As String
    Public Property nom_banco As String
    Public Property fecha_pago As Nullable(Of Date)
    Public Property resultado As String
    Public Property tipo_pago As String
    Public Property estado As String
    Public Property orden_ingreso As String
    Public Property url As String
    Public Property año As Nullable(Of Integer)
    Public Property num_parte As Nullable(Of Integer)
    Public Property juzgado As String
    Public Property datetime As Nullable(Of Date)
    Public Property rut_tes As String
    Public Property fecha_citacion As String
    Public Property estado_pago As String
    Public Property id_multas As Integer

End Class
